name: Bug Report
description: Create a report to help us improve
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: First, tell us which component we should focus on
      options:
        - I don't know
        - Quickstart
        - Helm Chart
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what's wrong
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: I did (A), then (B) and then I saw (C) error
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context or screenshots
      description: Add any other context about the problem here
      placeholder: Anything else you want to say to the report, attach screenshots, this is the place
