apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama-32-3b-instruct
  name: llama-32-3b-instruct-inference-pool
  namespace: e2e-helm
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: llama-32-3b-instruct-epp-service
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama-32-3b-instruct
  targetPortNumber: 8000
