apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-picker-rolebinding
subjects:
- kind: ServiceAccount
  name: endpoint-picker-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-picker-role
