{{- if .Values.sampleApplication.enabled -}}
apiVersion: llm-d.ai/v1alpha1
kind: ModelService
metadata:
  name: {{ include "sampleApplication.sanitizedModelName" . }}
  labels: {{ include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: sample-application
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  decoupleScaling: false
  baseConfigMapRef:
    name: {{ include "modelservice.fullname" . }}-basic-gpu-with-nixl-preset
  routing:
    modelName: {{ include "sampleApplication.sanitizedModelName" . }}
  {{- include "sampleApplication.modelArtifacts" . | nindent 2 }}
  decode:
    replicas: 1
    containers:
    - name: "vllm"
      args:
      - "--served-model-name"
      - {{ include "sampleApplication.modelName" . }},{{ include "sampleApplication.sanitizedModelName" .}}
      resources: {{ .Values.sampleApplication.resources | toYaml | nindent 8 }}
  prefill:
    replicas: 1
    containers:
    - name: "vllm"
      args:
      - "--served-model-name"
      - {{ include "sampleApplication.modelName" . }},{{ include "sampleApplication.sanitizedModelName" .}}
      resources: {{ .Values.sampleApplication.resources | toYaml | nindent 8 }}
{{- end }}
