{{- if and .Values.gateway.enabled (eq .Values.ingress.enabled false) (eq .Values.gateway.serviceType "NodePort") .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels: {{ include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/gateway: {{ include "gateway.fullname" . }}
    app.kubernetes.io/component: sample-application
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.route.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.route.annotations "context" $) | nindent 4 }}
    {{- end }}
  name: {{ include "gateway.fullname" . }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end}}
  path: {{ .Values.route.path }}
  port:
    targetPort: default
  to:
    kind: Service
    name: {{ include "gateway.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
