apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-3.2-3b-instruct-pvc
  namespace: llm-d
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Gi
  storageClassName: glusterfile
