# yaml-language-server: $schema=values.schema.json

# Default values for the llm-d chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Global parameters
# Global Docker image parameters
# Please, note that this will override the image parameters, including dependencies, configured to use the global value
# Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
# @default -- See below
global:
  # -- Global Docker image registry
  imageRegistry: ""

  # @schema
  # items:
  #   type: string
  # @schema
  # -- Global Docker registry secret names as an array
  # </br> E.g. `imagePullSecrets: [myRegistryKeySecretName]`
  imagePullSecrets: []

  security:
    allowInsecureImages: true


# @schema
# additionalProperties: true
# @schema
# -- Parameters for bitnami.common dependency
common: {}

# -- Common parameters
# -- Override Kubernetes version
kubeVersion: ""

# -- String to partially override common.names.fullname
nameOverride: ""

# -- String to fully override common.names.fullname
fullnameOverride: ""

# -- Default Kubernetes cluster domain
clusterDomain: cluster.local

# @schema
# additionalProperties: true
# @schema
# -- Labels to add to all deployed objects
commonLabels: {}

# @schema
# additionalProperties: true
# @schema
# -- Annotations to add to all deployed objects
commonAnnotations: {}

# @schema
# items:
#   type: [string, object]
# @schema
# -- Array of extra objects to deploy with the release
extraDeploy: []

# -- Helm tests
test:

  # -- Enable rendering of helm test resources
  enabled: false

  # @default -- See below
  image:

    # -- Test connection pod image registry
    registry: quay.io

    # -- Test connection pod image repository. Note that the image needs to have both the `sh` and `curl` binaries in it.
    repository: curl/curl

    # -- Test connection pod image tag. Note that the image needs to have both the `sh` and `curl` binaries in it.
    tag: latest

    # -- Specify a imagePullPolicy
    imagePullPolicy: "Always"

    # @schema
    # items:
    #   type: string
    # @schema
    # -- Optionally specify an array of imagePullSecrets (evaluated as templates)
    pullSecrets: []

# -- Sample application deploying a p-d pair of specific model
# @default -- See below
sampleApplication:

  # -- Enable rendering of sample application resources
  enabled: true

  # -- Name of the base configMapRef to use
  # <br /> For the available presets see: `templates/modelservice/presets/`
  baseConfigMapRefName: basic-gpu-with-nixl-and-redis-lookup-preset

  model:
    # -- Fully qualified model artifact location URI
    # <br /> For Hugging Face models use: `hf://<organization>/<repo>`
    # <br /> For models located on PVC use: `pvc://<pvc_name>/<path_to_model>`
    modelArtifactURI: hf://meta-llama/Llama-3.2-3B-Instruct

    # -- Name of the model
    modelName: "meta-llama/Llama-3.2-3B-Instruct"

    # -- Aliases to the Model named vllm will serve with
    servedModelNames: []

    auth:

      # -- HF token auth config via k8s secret.
      hfToken:

        # -- Name of the secret to create to store your huggingface token
        name: llm-d-hf-token

        # -- Key within the secret under which the token is located
        key: HF_TOKEN

  # @schema
  # $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/_definitions.json#/definitions/io.k8s.api.core.v1.ResourceRequirements
  # @schema
  # -- Modify resource limits/requests available to the pods
  # -- Resource requests/limits
  # <br /> Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"

  # -- InferencePool port configuration
  inferencePoolPort: 8000

  prefill:
    # -- number of desired prefill replicas
    replicas: 1

    # @schema
    # items:
    #   type: string
    # @schema
    # -- args to add to the prefill deployment
    extraArgs: []

    # -- environment variables injected into each decode vLLM container
    env: []

  decode:
    # -- number of desired decode replicas
    replicas: 1

    # @schema
    # items:
    #   type: string
    # @schema
    # -- args to add to the decode deployment
    extraArgs: []

    # -- environment variables injected into each decode vLLM container
    env: []

  endpointPicker:

    # @schema
    # items:
    #   $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/_definitions.json#/definitions/io.k8s.api.core.v1.EnvVar
    # @schema
    # -- Apply additional env variables to the endpoint picker deployment
    # <br /> Ref: https://github.com/neuralmagic/llm-d-inference-scheduler/blob/0.0.2/docs/architecture.md
    env: []

# -- Gateway configuration
# @default -- See below
gateway:

  # -- Deploy resources related to Gateway
  enabled: true

  # --  String to fully override gateway.fullname
  fullnameOverride: ""

  # -- String to partially override gateway.fullname
  nameOverride: ""

  # -- Gateway class that determines the backend used
  # Currently supported values: "kgateway" or "istio"
  gatewayClassName: istio

  # @schema
  # additionalProperties: true
  # @schema
  # -- Additional annotations provided to the Gateway resource
  annotations: {}

  # Special parameters applied to kGateway via GatewayParameters resource
  kGatewayParameters:
    # @schema
    # type: [number, boolean]
    # @schema
    proxyUID: false

  # @schema
  # items:
  #  type: object
  #  properties:
  #    name:
  #      description: Name is the name of the Listener. This name MUST be unique within a Gateway
  #      type: string
  #    path:
  #      description: Path to expose via Ingress
  #      type: string
  #    port:
  #      description: Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules
  #      type: integer
  #      minimum: 1
  #      maximum: 65535
  #    protocol:
  #      description: Protocol specifies the network protocol this listener expects to receive
  #      type: string
  # @schema
  # Set of listeners exposed via the Gateway, also propagated to the Ingress if enabled
  listeners:
    - name: default
      path: /
      port: 80
      protocol: HTTP

  # -- Gateway's service type. Ingress is only available if the service type is set to NodePort. Accepted values: ["LoadBalancer", "NodePort"]
  serviceType: NodePort

# -- Ingress configuration
# @default -- See below
ingress:

  # -- Deploy Ingress
  enabled: true

  # -- Name of the IngressClass cluster resource which defines which controller will implement the resource (e.g nginx)
  ingressClassName: ""

  # @schema
  # additionalProperties: true
  # @schema
  # -- Additional annotations for the Ingress resource
  annotations: {}

  # -- Hostname to be used to expose the NodePort service to the inferencing gateway
  host: ""

  # -- List of additional hostnames to be covered with this ingress record (e.g. a CNAME)
  # <!-- E.g.
  # extraHosts:
  #   - name: llm-d.env.example.com
  #     path: / (Optional)
  #     pathType: Prefix (Optional)
  #     port: 7007 (Optional) -->
  extraHosts: []

  # -- Path to be used to expose the full route to access the inferencing gateway
  path: "/"

  # -- Ingress TLS parameters
  tls:

    # -- Enable TLS configuration for the host defined at `ingress.host` parameter
    enabled: false

    # -- The name to which the TLS Secret will be called
    secretName: ""

  # @schema
  # items:
  #   $ref: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/_definitions.json#/definitions/io.k8s.api.networking.v1.IngressTLS
  # @schema
  # -- The TLS configuration for additional hostnames to be covered with this ingress record.
  # <br /> Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  # <!-- E.g.
  # extraTls:
  #   - hosts:
  #     - llm-d.env.example.com
  #     secretName: llm-d-env -->
  extraTls: []

  # -- used as part of the host dirivation if not specified from OCP cluster domain (dont edit)
  clusterRouterBase: ""

# -- Modelservice Sub Charts
llm-d-modelservice:
  multinode: true
  inferencePool: true
  inferenceModel: true
  httpRoute: true
  routing:
    modelName: meta-llama/Llama-3.2-3B-Instruct
    servicePort: 8080   # Sidecar listens on this port for requests. If there's no sidecar, the request goes here
    proxy:
      image:
        registry: "ghcr.io"
        repository: "llm-d/llm-d-routing-sidecar"
        tags: "0.0.6"
      targetPort: 8200
      debugLevel: 5
    parentRefs:
    - name: inference-gateway # this part needs to be dealt with moving to the upstream charts

  modelArtifacts:
    # When specifying the URI with `hf` prefix, the <repo-id>/<model-id> string
    # is extracted and exposed as a template variable that can be used as {{ .HFModelName }}

    uri: "hf://meta-llama/Llama-3.2-3B-Instruct"
    authSecretName: "llm-d-hf-token"
    size: 5Mi

  # describe decode pods
  decode:
    enableService: false
    replicas: 1
    containers:
    - name: "vllm"
      image: "ghcr.io/llm-d/llm-d:0.0.8"
      command:
        - vllm
        - serve
      args:
        - "--enforce-eager"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: UCX_TLS
          value: "cuda_ipc,cuda_copy,tcp"
        - name: HF_HOME
          value: /model-cache
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VLLM_NIXL_SIDE_CHANNEL_PORT
          value: "5557"
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
      ports:
        - containerPort: 5557
          protocol: TCP
      resources:
        limits:
          memory: 16Gi
          cpu: "16"
          nvidia.com/gpu: "1"
        requests:
          cpu: "16"
          memory: 16Gi
          nvidia.com/gpu: "1"
      mountModelVolume: true

  # describe prefill pods
  prefill:
    replicas: 1
    containers:
    - name: "vllm"
      image: "ghcr.io/llm-d/llm-d:0.0.8"
      command:
        - vllm
        - serve
      args:
        - "--enforce-eager"
        - "--kv-transfer-config"
        - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: UCX_TLS
          value: "cuda_ipc,cuda_copy,tcp"
        - name: VLLM_NIXL_SIDE_CHANNEL_PORT
          value: "5557"
        - name: VLLM_NIXL_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
      ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
      resources:
        limits:
          memory: 16Gi
          cpu: "16"
          nvidia.com/gpu: "1"
        requests:
          cpu: "16"
          memory: 16Gi
          nvidia.com/gpu: "1"

  endpointPicker:
    image: ghcr.io/llm-d/llm-d-inference-scheduler:0.0.4
    debugLevel: 5
    service:
      type: ClusterIP
      port: 9002
      targetPort: 9002
      appProtocol: http2
    # The name of cluster role containing permissions to be granted to endpointPicker (via a role binding to the service account)
    permissions: pod-read

    autoscaling:
      enabled: false
    replicas: 1


# @schema
# $ref: https://raw.githubusercontent.com/bitnami/charts/refs/tags/redis/20.13.4/bitnami/redis/values.schema.json
# @schema
# -- Bitnami/Redis chart configuration
# @default -- Use sane defaults for minimal Redis deployment
redis:
  enabled: true
  auth:
    enabled: false
    existingSecretPasswordKey: ""
    existingSecret: ""
  architecture: standalone
  image:
    registry: quay.io
    repository: sclorg/redis-7-c9s
    tag: c9s
  master:
    kind: Deployment
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    persistence:
      enabled: false
    pdb:
      create: false
    service:
      ports:
        redis: 8100
  networkPolicy:
    enabled: false
