test:
  enabled: true

sampleApplication:
  enabled: false

redis:
  master:
    persistence:
      enabled: false

modelservice:
  metrics:
    enabled: false
  epp:
    extraEnvVars:
      - name: PD_ENABLED
        value: 'false'
